run: -1
load_last: True
run_dir: "runs/crop_transformer/"
crop_dataset_path: "data/argo_dataset/argo_dataset.csv"
random_seed: 1337
context_size: 256
batch_size: 16
epochs: 100000
learning_rate: 1e-6
optimizer_type: "Adam"
saving_freq: 1000
save_path: "models/checkpoint_model"
validation_freq: 100
count_validation_steps: 5
generation_freq: 100
use_comet: True